### ISSUE TITLE
Error opening .parquet file

### ISSUE THREAD

**Issue by theroggy** [mukunku/ParquetViewer#8] opened 2019-07-24 07:31 UTC
Larger .parquet files give ArgumentOutOfRangeException" error for me, just like mentioned in closed ticket #5.

For me, it isn't an urgent issue, as I transitioned to .sqlite files for some other technical reasons, but as it might be usefull for you or other users... but as you asked for example files in the now closed tickets.

The .parquet file was created using pyarrow in python, and I tested in ParquetViewer 1.1:
https://drive.google.com/open?id=12vIw3f5tMURfzhI6hO3clHtPafPwhqnq

![ParquetViewer_2019-07-24_09-27-55](https://user-images.githubusercontent.com/1565789/61773890-fe817300-adf5-11e9-8f7a-74a1f07cc5e9.png)

**Comment by jvasekpn** [comment] 2019-08-01 20:39
I am also experiencing this issue
![image](https://user-images.githubusercontent.com/45108468/62325947-86a8ed80-b472-11e9-867e-e46d19edbdb2.png)

**Comment by mukunku** [comment] 2019-08-10 19:38
The application is still using the old v1 Parquet.Net library which does not support many complicated parquet files. I will look into updating to the latest version but this will require a major re-write as the newer versions have changed dramatically.

**Comment by mukunku** [comment] 2019-08-11 03:11
Please try the new beta release: https://github.com/mukunku/ParquetViewer/releases/tag/v2.0

I was able to load the above parquet file using this new version. Keep in mind that this is a beta release so all the features have not been fully tested.

**Comment by jvasekpn** [comment] 2019-08-11 03:37
Thank you very much.  I will definitely be testing it out on Monday.
________________________________

**Comment by jvasekpn** [comment] 2019-08-12 14:07
I am now getting a different error message after clicking done on this UI:
![image](https://user-images.githubusercontent.com/45108468/62871150-86191e00-bce0-11e9-93f9-3367a2a3784b.png)

![image](https://user-images.githubusercontent.com/45108468/62871174-96c99400-bce0-11e9-8d34-c1af6828c7c4.png)

If necessary I can provide a sample file for testing.

**Comment by mukunku** [comment] 2019-08-12 14:19
Yes, Can you please provide a sample?

On Aug 12, 2019, at 10:07 AM, jvasekpn <notifications@github.com<mailto:notifications@github.com>> wrote:


I am now getting a different error message after clicking done on this UI:
[image]<https://user-images.githubusercontent.com/45108468/62871150-86191e00-bce0-11e9-93f9-3367a2a3784b.png>

[image]<https://user-images.githubusercontent.com/45108468/62871174-96c99400-bce0-11e9-8d34-c1af6828c7c4.png>

If necessary I can provide a sample file for testing.

**Comment by jvasekpn** [comment] 2019-08-12 14:29
Absolutely.  I have generated a sample of random data using a library called "parquetjs".
![image](https://user-images.githubusercontent.com/45108468/62872638-81a23480-bce3-11e9-95ea-0ffe7439476c.png)

And here is the sample file in a ZIP archive:
[sample.zip](https://github.com/mukunku/ParquetViewer/files/3492926/sample.zip)

**Comment by mukunku** [comment] 2019-08-12 23:09
Seems like Parquet.NET has issues opening these files. I took a look at ParquetJS and looks like the data types are not standard, at least as far as I can tell.

Unfortunately there isn't much I can do at this time unless the issue is resolved in the Parquet.Net library: https://github.com/elastacloud/parquet-dotnet

You can open a ticket with the Parquet.Net library if you'd like. Or if it's okay to share your sample file I can open the ticket for you.

**Comment by jvasekpn** [comment] 2019-08-13 00:25
You may share the sample file.  Thank you for looking into this for me! That sample file only contains random data.
________________________________

**Comment by mukunku** [comment] 2019-08-15 14:17
I created the following ticket: https://github.com/elastacloud/parquet-dotnet/issues/429
Let's see if someone can take a look.

**Comment by mukunku** [comment] 2019-08-15 14:57
As replied by the parquet.net owner: https://github.com/elastacloud/parquet-dotnet/issues/429
It seems the parquet file is not valid as per even the native Java standards. So not much can be done on our side for this. I'm closing this ticket as fixed as the original issue has been fixed.

**Closed by mukunku** 2019-08-15 14:57 UTC
Labels: bug

**Comment by theroggy** [comment] 2019-08-25 19:01
Indeed the file I had issues with loads without problems now. Thanks!
