### ISSUE TITLE
[BUG] Close button is not at the top right

### ISSUE THREAD

**Issue by Caceresenzo** [mukunku/ParquetViewer#56] opened 2022-08-11 15:19 UTC
**Parquet Viewer Version**
v2.3.6

**Describe the bug**
The window's close button is not exactly at the top right of the page.
Clicking exactly at the right close windows behind.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/7386242/184168465-c98467cc-01a7-42f0-bdb6-88c8ba1eec36.gif)

**Additional context**
You must be exactly at the very very top right.
It must be only a 1px gap.

**Comment by mukunku** [comment] 2022-08-13 04:51
It's not that way for me on Windows 10:
![image](https://user-images.githubusercontent.com/4502154/184468990-79a53d70-e0d4-490b-ad10-a461b49dd56b.png)

Which OS are you on? Also, could you test it with the latest beta release? Maybe it's fixed now for you: https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.7

**Comment by keen85** [comment] 2022-08-13 08:36
I can confirm that also on Windows 10 with the [v2.3.7 pre-release](https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.7) there is 2px gap if the window is **maximized**.
### However:
- even when hovering over the 2px gap, the button is targeted nonetheless. If I place my cursor in the top right corner of my screen and click, the application is closed. So, I can't replicate the original issue of @Caceresenzo.
- also other applications (e.g. notepad, taskmanager, mspaint) show the same behavior: if the windows is maximized, there is a visual gap 
![image](https://user-images.githubusercontent.com/29750255/184476019-31565449-53df-4edd-a654-1be7e1d721a5.png)

**Comment by mukunku** [comment] 2022-08-13 12:39
Thanks for the info @keen85 .I saw similar behavior when testing locally: there is a gap when full screen but I can still close the window at the top right of the screen.  Lets see what OP says. Maybe @Caceresenzo has a second monitor that is off screen which is causing the issue for them, maybe?

Honestly we're just using the default WinForms UI here so not sure if there's anything that can be done to change how the "X" is rendered on the window.

**Comment by Caceresenzo** [comment] 2022-08-13 15:27
Sorry for the late answer.

Yes you are right.
I am on Windows 10, using a second 2560x1440 monitor with 125% scale, and the problem is when the application is maximized.

The [v2.3.7 pre-release](https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.7) hasn't fixed the problem for me.

**Comment by mukunku** [comment] 2023-01-29 21:06
Hey @Caceresenzo , the latest beta release has been built with .NET 7 which has changed some fundamental stuff around WinForms rendering. Can you give this version a try and see if the issue is maybe fixed for you now?

https://github.com/mukunku/ParquetViewer/releases/tag/v2.5.1

**Comment by Caceresenzo** [comment] 2023-01-31 10:59
The gap still seems to be here:
![image](https://user-images.githubusercontent.com/7386242/215742005-75e225de-991a-4eb9-b7f8-e9e1b8e7441a.png)

But now the mouse will always "click on it". So its not an issue anymore?

Thanks a lot for your update @mukunku

**Comment by mukunku** [comment] 2023-01-31 13:47
Yay 🙌🏼 At least it works for you now. Closing out this ticket.

**Closed by mukunku** 2023-01-31 13:47 UTC
Labels: bug
