### ISSUE TITLE
[FEATURE-REQUEST] Ability to sort data by columns

### ISSUE THREAD

**Issue by bytedynamic** [mukunku/ParquetViewer#46] opened 2021-10-23 16:29 UTC
Latest version(v2.3.5) no support for sort data by columns.  Can it be supported?

**Comment by mukunku** [comment] 2022-08-13 04:56
So I took another look at this and we do have sorting by column. But it's only for the records that are loaded onto the screen. So you can simply sort by clicking on any column header. However I can't add sorting across the entire file as that would require reading all the data first and sorting it. So closing out this ticket as "working as intended"

**Closed by mukunku** 2022-08-13 04:56 UTC
Labels: enhancement, wontfix
