### ISSUE TITLE
[FEAT] Time Decimals (milliseconds) in CSV export

### ISSUE THREAD

**Issue by Amin-AppliedPhilo** [mukunku/ParquetViewer#51] opened 2022-03-09 21:03 UTC
when opening a file, it shows the Time format to many decimal points
but when exporting the same data, it does not "honour" the time format and only saves down to a second, 

Would you please kindly maybe one day make the export function also put in the extra decimal figures in the CSV? 

hugs and kisses
Amin

**Describe the feature you'd like to be added to Parquet Viewer**
Provide as much detail as possible.

**Share why this feature would be a good addition to the utility**
Will it improve usability, reliability or some other aspect?

**Screenshots**
Any screenshots describing how the feature would look is a plus.

Note: There are no guarantees your feature will be implemented.

**Comment by mukunku** [comment] 2022-08-13 04:54
With the latest release the exported file's date formats will match what's displayed in the UI. I also added a bunch of different date formats as well as an export to Excel option (although I can't take full credit for the Excel export part).

https://github.com/mukunku/ParquetViewer/releases/tag/v2.3.7

**Comment by mukunku** [comment] 2022-08-13 04:56
Closing out for now. Can re-open if the issue is still there.

**Closed by mukunku** 2022-08-13 04:56 UTC
Labels: enhancement
